import type { NextPage } from 'next';
import Head from 'next/head';
import Hero from 'src/components/Hero';

import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import { SliderData } from '../components/Slider/data';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Photography Portfolio Website</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <Hero
      heading='Captur Photography'
      message='I capture moments in nature and keep them alive.'
    />
    <Slider slides={SliderData} />
    <Instagram />
  </div>
);

export default Home;
